What is your name? How many hours did you work this week? What is your hourly payrate? 
Hello Alice
Your gross pay is $597.500000
[36m╷[0m
[36m├─[0m [36mJUnit Jupiter[0m [32m✔[0m

[         0 tests found           ]
[         0 tests skipped         ]
[         0 tests started         ]
[         0 tests aborted         ]
[         0 tests successful      ]
[         0 tests failed          ]
