0
1
2
3
4
5
6
7
8
9
0
1
2
3
4
6
7
8
9
p1 (0) is less than p2 (10)
0
1
2
3
4
5
6
7
8
9
p2 (0) is less than p1 (10)
[36m╷[0m
[36m├─[0m [36mJUnit Jupiter[0m [32m✔[0m
[36m│  └─[0m [36mMain[0m [32m✔[0m
[36m│     ├─[0m [34mtest0()[0m [32m✔[0m
[36m│     └─[0m [34mtest1()[0m [32m✔[0m

[         2 tests found           ]
[         0 tests skipped         ]
[         2 tests started         ]
[         0 tests aborted         ]
[         2 tests successful      ]
[         0 tests failed          ]

