[36m╷[0m
[36m├─[0m [36mJUnit Jupiter[0m [32m✔[0m
[36m│  └─[0m [36mMain[0m [32m✔[0m
[36m│     ├─[0m [34mtest0()[0m [32m✔[0m
[36m│     ├─[0m [34mtest1()[0m [32m✔[0m
[36m│     └─[0m [34mtest2()[0m [32m✔[0m

[         3 tests found           ]
[         0 tests skipped         ]
[         3 tests started         ]
[         0 tests aborted         ]
[         3 tests successful      ]
[         0 tests failed          ]

Hello
FAILED
