[36m╷[0m
[36m├─[0m [36mJUnit Jupiter[0m [32m✔[0m
[36m│  └─[0m [36mMain[0m [32m✔[0m
[36m│     ├─[0m [34mtest0()[0m [32m✔[0m
[36m│     ├─[0m [34mtest1()[0m [32m✔[0m
[36m│     ├─[0m [34mtest2()[0m [32m✔[0m
[36m│     ├─[0m [31mtest3()[0m [31m✘[0m [31mexpected: <0> but was: <0.0>[0m
[36m│     ├─[0m [34mtest4()[0m [32m✔[0m
[36m│     └─[0m [31mtest5()[0m [31m✘[0m [31mexpected: <1.0E-4> but was: <9.999999999998899E-5>[0m

Failures (2):
  JUnit Jupiter:Main:test3()
    MethodSource [className = 'Main', methodName = 'test3', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: expected: <0> but was: <0.0>
       org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
       org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:195)
       org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:184)
       org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:179)
       org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
       Main.test3(Main.java:56)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       java.base/java.lang.reflect.Method.invoke(Method.java:566)
       [...]
  JUnit Jupiter:Main:test5()
    MethodSource [className = 'Main', methodName = 'test5', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: expected: <1.0E-4> but was: <9.999999999998899E-5>
       org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
       org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:195)
       org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:184)
       org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:179)
       org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:898)
       Main.test5(Main.java:64)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       java.base/java.lang.reflect.Method.invoke(Method.java:566)
       [...]

Test run finished after 102 ms
[         6 tests found           ]
[         0 tests skipped         ]
[         6 tests started         ]
[         0 tests aborted         ]
[         4 tests successful      ]
[         2 tests failed          ]

