[36m╷[0m
[36m├─[0m [36mJUnit Jupiter[0m [32m✔[0m
[36m│  └─[0m [36mMain[0m [32m✔[0m
[36m│     ├─[0m [31mtest0()[0m [31m✘[0m [31mexpected: <3> but was: <3.0>[0m
[36m│     └─[0m [34mtest1()[0m [32m✔[0m

Failures (1):
  JUnit Jupiter:Main:test0()
    MethodSource [className = 'Main', methodName = 'test0', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: expected: <3> but was: <3.0>
       org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
       org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:195)
       org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:184)
       org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:179)
       org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
       Main.test0(Main.java:22)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       java.base/java.lang.reflect.Method.invoke(Method.java:566)
       [...]

Test run finished after 85 ms
[         2 tests found           ]
[         0 tests skipped         ]
[         2 tests started         ]
[         0 tests aborted         ]
[         1 tests successful      ]
[         1 tests failed          ]

