line 1:6 extraneous input '1' expecting ')'
line 2:0 missing '{' at 'print'
line 10:0 missing '}' at '<EOF>'
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.github.lessjava.visitor.impl.LJInstantiateFunctions.instantiateFunction(LJInstantiateFunctions.java:88)
	at com.github.lessjava.visitor.impl.LJInstantiateFunctions.postVisit(LJInstantiateFunctions.java:57)
	at com.github.lessjava.types.ast.ASTFunctionCall.traverse(ASTFunctionCall.java:41)
	at com.github.lessjava.types.ast.ASTVoidFunctionCall.traverse(ASTVoidFunctionCall.java:13)
	at com.github.lessjava.types.ast.ASTBlock.traverse(ASTBlock.java:27)
	at com.github.lessjava.types.ast.ASTFunction.traverse(ASTFunction.java:23)
	at com.github.lessjava.types.ast.ASTProgram.traverse(ASTProgram.java:37)
	at com.github.lessjava.LJCompiler.main(LJCompiler.java:101)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command '/usr/lib64/openjdk-8/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
